HMIS-1165 HMIS-1167 - Rota re-write
hmcts/hmi-rota-dtu pull request #39
Opened 2023-05-05 14:31 UTC by joshblackmoor

### JIRA link (if applicable) ###

https://tools.hmcts.net/jira/browse/HMIS-1165
https://tools.hmcts.net/jira/browse/HMIS-1167

### Change description ###

Re-write of rota logic app for MVP.

**Does this PR introduce a breaking change?** (check one with "x")

```
[ ] Yes
[x] No
```

2023-05-09 10:18 UTC, KianKwa commented on src/main/java/uk/gov/hmcts/reform/hmi/service/ConversionService.java
> +                ObjectMapper mapper = new ObjectMapper();
Better to move the creation of ObjectMapper out of the loop. This can be a constant object and doesn't need to be instantiated for every CLP ID.

2023-05-09 10:20 UTC, KianKwa commented on src/main/java/uk/gov/hmcts/reform/hmi/service/ProcessingService.java
> +            districtJudges.forEach(districtJudge -> {
This forEach loop here and the one before look identical. May be can remove one of them but instead call handleJusticesToModel() twice, once with the magistrates and then with district judges?

2023-05-10 14:12 UTC, ChrisS1512 requested changes

2023-05-11 10:56 UTC, joshblackmoor commented on src/main/java/uk/gov/hmcts/reform/hmi/service/ConversionService.java
> +        if (!uniqueClpIds.isEmpty()) {
Done

2023-05-11 10:56 UTC, joshblackmoor commented on src/main/java/uk/gov/hmcts/reform/hmi/models/external/Judge.java
> +
Done

2023-05-11 10:56 UTC, joshblackmoor commented on src/main/java/uk/gov/hmcts/reform/hmi/service/ConversionService.java
> +                ObjectMapper mapper = new ObjectMapper();
Done

2023-05-11 11:00 UTC, joshblackmoor commented on config/owasp/suppressions.xml
> +  <suppress>
Done

2023-05-11 11:13 UTC, joshblackmoor commented on src/main/java/uk/gov/hmcts/reform/hmi/service/ConversionService.java
> +                HmiJsonRequest hmiJsonRequest = new HmiJsonRequest();
Done

2023-05-12 09:23 UTC, ChrisS1512 approved these changes

2023-05-12 09:25 UTC, merged